# Generated by Django 4.0.3 on 2023-01-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
